language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: KGbHGdZMgSg+k8wxq0X1C5uxdFi/eybAi+2D/2dsiU9sPvOsUnQFfJUpTAHG6hO5InkDM8JHQc2ErN2uBe1PpWBUZV4ybTTSgP3Bqfl85tX9nGv1SIzMNP/MYUSlBl/LeKTtK9F6T/+fhkqCzCfHigkFne1nhcu+IFtFRMOxQPvo0Wc+UAzWSXPnnsPbgKX2MvQyfUJeHAN8NJQXpCwefr2M4DYyeA8jI6VwPCs0uKBfBFqJjWZ2AiCxOITHp6ATuelM1SdhlnG85fckkEqmTkfUnm5TXkFkZIUljj1NtBxc0M+oKBKkyk5GHJdkUvTdx6rcyZ5+rg36PEZV+A4n0fVr5E65/Ro1SikwpyXyKG5NaBwYhLAHxPArOKvRrVIE70n1Sc3x6X9E7VQM9eMMEYmrq3vadFrt9AhhUqX7VxTSaf/MVIjckfQHuPtUBHMOVYOVmuh9xo9+CZkDfMJFgaHd01B2/CH6J59kUfUvOz3XWqEFmWAbn4ljIZRE+NwdRJz8/BzltrBCQwIK5w+cffTA03xXtdyY3c8lhXa9yvOJt2Z/dTG7ohX7qrbgsnwRODzjrrp0tMhqKbfpbU1PHLQzDsr3R448mVLHcigDmD1YZPcfXDTElYfIVP5o5RPPAXDRc9aq/T0+1BHgyXEPrOEvv4sMtX9QO+tXZapkCno=
  app: shielded-peak