language: java
jdk:
  - openjdk8
script: mvn clean verify
deploy:
  api_key:
    secure: vtS4NnZrNuK2HEwEld82+ubT9Xh9gTppR5d1jFLlbVgITm2XOkvGcs+H4CSuN/vuIIe4gc9tzA3doyKB8zP4zcqXUNaDoKQ0fPsO1mox9YOJPkTFUD2jclWTsqR5xIDvT6/K60Xk9z3SqR/0IgAhtdUnGyRbpupTltjCwPjUqmg9412eHftCjqNsx8mlCMFvXH0W9RpEWiIotRYB+RCfZjM6Kcc3UyaFaKNJerKjtKGKymFeRrjwC8YNELSUuOVthWUagkYrz2X0TlJXZmUszLHkfGRgNsBC7ZlB2/quc/O7T++lSG71EKWs38Ke59z1FcsxZfmlg9PhPZiXhNG6ea6sNlIe5yq0xHn9ufc38f9hNxe90mfp3TWnuT5o8thFxs2ietcmB2y2O+WIJSWXK8Sanx3QCEWy4MwVYbH4zDG3s4UdU4arSsEPCYWimEabFTutXWlKyINv3qgC/1Z1Kuf9MStpVFpRMhyCBkgQOiejj5fLCfw4ENPVmSPVGzhvRe2tchx4FRrAYLXMUINgNSGbV8EBa1eePhR00AX/k/EXETi8/Q5f8OyfqI8afxN6yUSCqrgbi1GH9c01lQ30wVjLWjLf0M1hgfPmAQ5iVaDmadt1hf7Pg7VLEVLU13NGR/2UyOc7UGXK+lW4xFju5TZBm5wtts2yx/9+jXAF/pU=
  app: shielded-peak-62517
