language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  app: shielded-peak-62517
  api_key:
    secure: N7KnPxo/SldpKTM1Ww0ItKsEjf6RiYvraCQHGcRWOnDjj+VtTH1SjfqpKILvhtJCCG/sAIhLoBsE+KP/JMjdzDNeG6gGT644Di+7g0yPdkux2GnGQ4JztVeBiJ4nRyWP+6fjLU4DEo50zBI+Y0XP1eekMj7owcNnHL+ZSJRUSClsOdeOwIstSFJieA32MNFhdTprIHBp7uHWLDh6Pl6ltVBMKXvo5HhMh3h1tuwBuWVk0bar4h/URfa2KZjYYZcEHp3/TEIxIVKmDAg58hbRIw+HeQdfAMPcsuWCIh+vOnezOfkj7z/DcrMy/vIW6cUGb2xJuCwyJgn6UcDCK7Yd9Kz8M1khuvIWnA9V9gx5woKE/diMyFeRsaEo2X783jhFWXWIKgNEC+bI3pLNOovx5l0m9mLb0CxE4vJE5g9Y5ci6nt+/wYpJUfQOdBFoHqfRQWCWgI4BXr8Oo8mTudIKtvT5NzmpdHO+TDYoK9nInEeHJi6DGatsTdlPm9edK+P5pT29aEtL5M82i8buSsjQx8LCYo8stDoBOUUu4gXfVyq3j/0bZoNXtrXNeFs3VmGUhw3WpJPsb04kVTtusVqxlU0ACERtvjYy0Vdo9ruU1ucP76BDLLWmHujoMNfiyTMHs8DcdmlywD52ufLzIMbYrDl9XQ4M9jYwAweFwRuxM04=
